news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx/
    queries:
      homepage_articles_links: 'h3.field-content a'
      article_body: '.field-name-body p'
      article_title: 'h1' 
  elpais:
    url: https://elpais.com/
    queries:
      homepage_articles_links: ''
      article_body: ''
      article_title: ''